name: Api Design
description: Something in the API is unclear and could be better
type: Enhancement
labels:
  - api design
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-is-it
    attributes:
      label: What it is?
      description: What doesn't make sense?
      placeholder: ex. Vector3 is not a good name for a vector
    validations:
      required: true

  - type: textarea
    id: what-should-it-be
    attributes:
      label: What should it be?
      description: What should it be instead?
      placeholder: ex. Vec3 is a better name because...
    validations:
      required: true