name: Feature request
description: Suggest an idea for this project
labels:
  - feature
body:
  - type: dropdown
    id: product
    attributes:
      label: For?
      multiple: true
      options:
        - S&Box
        - Hammer
        - Material Editor
        - Source Film Maker
        - Other
    validations:
      required: true
  - type: textarea
    id: what-cant-you-do
    attributes:
      label: What can't you do?
      description: Describe in detail what you're unable to currently do
      placeholder: I'm unable to...
    validations:
      required: true
  - type: textarea
    id: how-work
    attributes:
      label: How would you like it to work?
      description: Describe in detail how the feature should work
      placeholder: I want it to work by...
    validations:
      required: true
  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: >-
        Describe a few work arounds you have in place or what you have tried to
        do thus far.
      placeholder: I have tried...
    validations:
      required: true
  - type: textarea
    id: extra-context
    attributes:
      label: Additional context
      description: Any extra deails on the feature you're requesting